### ISSUE TITLE
Able to perform new user registration with existing Email ID/username

### ISSUE THREAD

**Issue by Hmittal15** [BigDataIA-Spring2023-Team-11/Assignment3#11]
**Expected Behavior**
If a user has already signed-in, they should not be able to register for a new account with same account identifiers, such as Email ID.

**Current Behavior**
Able to perform new user registration with existing Email ID/username.
![image](https://user-images.githubusercontent.com/108916132/225507508-565f9052-8394-4e0a-94f1-ee15577c7c08.png)
![image](https://user-images.githubusercontent.com/108916132/225507540-55d3f14e-6c05-4abd-80f4-bfa3cadb9020.png)

**Possible Solution**
Perform a validation for existing user before letting them register for a new account.

**Steps to Reproduce**
1. Navigate to 'Register' page.
2. Provide user account details to create a new account, and submit.
3. Refresh the page and try to register for a new user.
4. Provide same account details which were used in step 2, and submit.

**Possible Implementation**
When a user visits the 'Register' page, fetch the details enterred by them. Design a method to perform validation checks on the unique identifiers such as Email ID/username. If the details are already available in the user DB then prompt the user to provide different values and prevent registration.

**Comment by abhatt13** [comment]
<img width="1262" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/114257635/225787542-a88bc14e-a330-48c1-b761-c47d227ff3aa.png">
As per the above image, when I try to register with username "bhargavi", it is giving a prompt as User already exists. We are only having username as unique identifier not email. As per our application development needs we thought of keeping the username Unique instead of the email address.
