### ISSUE TITLE
Metadata not getting scraped on a regular basis

### ISSUE THREAD

**Issue by Hmittal15** [BigDataIA-Spring2023-Team-11/Assignment3#9]
**Expected Behavior**
Metadata from the NOAA public bucket should be scraped on a daily basis, so that user is provided with latest data regularly.

**Current Behavior**
Metadata not getting scraped on a regular basis. For NEXRAD, latest data available in the application for user is till 2023, Feb month. For Goes18, latest data available is till 2023, 39th day.
![image](https://user-images.githubusercontent.com/108916132/225504679-0cfa1777-1c46-4c08-afb5-f1bf46c3873c.png)
![image](https://user-images.githubusercontent.com/108916132/225504707-81a38044-5493-4aa0-b1fc-4824787f0cab.png)

**Possible Solution**
Create an Airflow DAG to read the NOAA bucket public metadata. Schedule this DAG to run everyday on a preset time using cronjob.

**Steps to Reproduce**
1. Login with an existing user.
2. Navigate to NEXRAD/Goes18 page.
3. Select the year filter.
4. Select the month/day filter.

**Possible Implementation**
Design a method to read the publicly available metadata from NOAA website. Store this metadata into a DB file on a cloud platform. Read this DB file everytime a user visits the front-end application. Deploy an Airflow DAG to update the metadata everyday on a pre-scheduled time.

**Comment by abhatt13** [comment]
<img width="1262" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/114257635/225786692-79300024-181d-4492-9acd-9469e89c9d9e.png">

As per the above image, when I try to register with username "bhargavi", it is giving a prompt as User already exists. We are only having username as unique identifier not email. As per our application development needs we thought of keeping the username Unique instead of the email address.

**Comment by charusingh-24** [comment]
The EC2 instance, which hosts the Airflow scheduler and the scheduled DAG, is not running 24*7, as a result, the DAG is not triggered at the scheduled hour, and data is not loaded as per the schedule. This approach is taken to optimize the cost associated with hosting the EC2 instance.
